post:
  tags:
    - Products
  summary: Список товаров (уценка)
  description: Получение списка товаров в уценке
  operationId: productsMarkdown
  requestBody:
    content:
      'application/json; charset=utf-8':
        schema:          
          type: object
          properties:
            login:
              type: string
            password:
              type: string
            download:
              type: boolean
              description: Признак формирования списка товаров в XLSX-формате
          required:
            - login
            - password            
  responses:
    '200':
      description: OK
      content:
        'application/json; charset=utf-8':
          schema:
            type: array
            items:
              $ref: '../components/schemas/ProductInList.yaml'
               

