post:
  tags:
    - Product
  summary: Данные по товару
  description: Получение данных по выбранному товару
  operationId: product
  requestBody:
    content:
      'application/json; charset=utf-8':
        schema:          
          type: object
          properties:
            login:
              type: string
            password:
              type: string
            code:
              type: string
              description: Код товара
          required:
            - login
            - password            
            - code
  responses:
    '200':
      description: OK
      content:
        'application/json; charset=utf-8':
          schema:            
            $ref: '../components/schemas/Product.yaml'
               

