post:
  tags:
    - Settings
  summary: Настройки пользователя
  description: Установка и чтение настроек
  operationId: settings
  requestBody:
    content:
      'application/json; charset=utf-8':
        schema:          
          type: object
          properties:
            login:
              type: string
            password:
              type: string
            ordersColumns:
              type: array
              description: Необходимый порядок и использование колонок на странице "Заказы"
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: Техническое имя колонки
                  isUse:
                    type: boolean
                    description: Признак использования колонки
            basket:
              type: array
              description: Корзина для сохранения выбранного товара
              items:
                type: object
                properties:
                  code:
                    type: string
                    description: Код товара
                  count:
                    type: number
                    description: Количество товара
          required:
            - login
            - password                        
  responses:
    '200':
      description: OK
      content:
        'application/json; charset=utf-8':
          schema:            
            $ref: '../components/schemas/Settings.yaml'
               

